name: rocket
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.1.2
  pedantic: ^1.9.0
  flutter_cube: ^0.0.5
  flutter_map: ^0.9.0
  location: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
  - family: CustomIcons
    fonts:
    - asset: assets/icons/CustomIcons.ttf

  assets:
    - assets/rocket/saturn_v.mtl
    - assets/rocket/saturn_v.obj
    - assets/rocket/texture/body.png
    - assets/rocket/texture/motor.png
    - assets/rocket/texture/shroud.png
